package ua.mytnyk.qrbot.domain;

public enum AnalyticsAction {
    MAIN_MENU_VIEWED,
    CREATION_STARTED,
    QR_TYPE_SELECTED,
    CONTENT_SELECTED,
    CREATION_PASSWORD_SET,
    QR_CREATED,
    QR_LIST_VIEWED,
    QR_PREVIEWED,
    QR_DELETED,
    QR_SCANNED,
    QR_NOT_FOUND,
    PASSWORD_REQUESTED,
    PASSWORD_REJECTED,
    CONTENT_DELIVERED,
    ONE_TIME_REDEEMED
}
